### ISSUE TITLE
webpage content overlays the navbar

### ISSUE THREAD

**Issue by kylelmh** [void-linux/void-linux.github.io#177] opened 2022-07-04 14:02 UTC
Current behavior:
![image](https://user-images.githubusercontent.com/59222981/177170082-f0516a40-00e8-474b-8bc2-e5fedba06f2b.png)
- When there is text over the navbar, the links become unclickable, I think this is not the desired behavior

expected behavior:
![image](https://user-images.githubusercontent.com/59222981/177170198-d59526f9-885a-4fdf-9ba1-5962a48b4533.png)

If this is actually an issue, I'll create a PR

**Comment by paper42** [comment] 2022-07-04 14:03
probably duplicate of #168

**Closed** 2022-07-04 14:06 UTC
